// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDT_gmV7wQtomkQoSMcqzc-BJtsgpQjOq4',
    appId: '1:780714473574:ios:c27600d800c7123d7995a7',
    messagingSenderId: '780714473574',
    projectId: 'tourismprototype',
    storageBucket: 'tourismprototype.firebasestorage.app',
    iosBundleId: 'q',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDT_gmV7wQtomkQoSMcqzc-BJtsgpQjOq4',
    appId: '1:780714473574:ios:027049e9c399c9367995a7',
    messagingSenderId: '780714473574',
    projectId: 'tourismprototype',
    storageBucket: 'tourismprototype.firebasestorage.app',
    iosBundleId: 'com.alia.tourismprot',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYFNQ2XJYU5fKdS1Ocf97YibSz3DWIhH8',
    appId: '1:780714473574:web:744d89dc591b86b47995a7',
    messagingSenderId: '780714473574',
    projectId: 'tourismprototype',
    authDomain: 'tourismprototype.firebaseapp.com',
    databaseURL: 'https://tourismprototype-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'tourismprototype.firebasestorage.app',
    measurementId: 'G-Q1K5C80J03',
  );

}